-- ============================================================================
-- Vue : V_MG_RECAP_COMPLET
-- Description : Récapitulatif AGENTS + RESSOURCES avec totaux par mission
-- Utilisation : Statistiques complètes incluant Police et Chauffeur ressources
-- ============================================================================

CREATE OR REPLACE VIEW V_MG_RECAP_COMPLET AS
SELECT 
    m.ID_ORDRE_MISSION,
    m.NUMERO_ORDRE_MISSION,
    m.OBJET_ORDRE_MISSION,
    m.DATE_DEBUT_PREVUE_ORDRE_MISSIO AS DATE_DEBUT,
    m.DATE_FIN_PREVUE_ORDRE_MISSION AS DATE_FIN,
    m.STATUT_ORDRE_MISSION,
    
    -- Calcul durée
    (m.DATE_FIN_PREVUE_ORDRE_MISSION - m.DATE_DEBUT_PREVUE_ORDRE_MISSIO + 1) AS DUREE_JOURS,
    (m.DATE_FIN_PREVUE_ORDRE_MISSION - m.DATE_DEBUT_PREVUE_ORDRE_MISSIO) AS DUREE_NUITS,
    
    -- Nombre participants (agents + ressources Police/Chauffeur)
    (SELECT COUNT(DISTINCT ID_AGENT) 
     FROM GM_PARTICIPER 
     WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION) AS NOMBRE_AGENTS,
     
    (SELECT COUNT(DISTINCT ID_RESSOURCE)
     FROM GM_UTILISER_RESSOUR ur
     INNER JOIN GM_RESSOURCE r ON ur.ID_RESSOURCE = r.ID_RESSOURCE
     WHERE ur.ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
     AND r.ID_TYPE_RESSOURCE IN (2, 3)) AS NOMBRE_RESSOURCES,
     
    ((SELECT COUNT(DISTINCT ID_AGENT) FROM GM_PARTICIPER WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION) +
     (SELECT COUNT(DISTINCT ID_RESSOURCE) FROM GM_UTILISER_RESSOUR ur
      INNER JOIN GM_RESSOURCE r ON ur.ID_RESSOURCE = r.ID_RESSOURCE
      WHERE ur.ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
      AND r.ID_TYPE_RESSOURCE IN (2, 3))) AS TOTAL_PARTICIPANTS,
    
    -- Totaux par catégorie (utilise GM_FRAISMISSION qui contient maintenant agents + ressources)
    NVL((SELECT SUM(MONTANT_PREVU__FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 1), 0) AS TOTAL_REPAS,
         
    NVL((SELECT SUM(MONTANT_PREVU__FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 2), 0) AS TOTAL_HEBERGEMENT,
         
    NVL((SELECT SUM(MONTANT_PREVU__FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 3), 0) AS TOTAL_INDEMNITE,
         
    NVL((SELECT SUM(MONTANT_PREVU__FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 4), 0) AS TOTAL_CARBURANT,
    
    -- Total général
    NVL((SELECT SUM(MONTANT_PREVU__FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION), 0) AS TOTAL_GENERAL
     
FROM 
    GM_ORDREMISSION m
WHERE 
    m.STATUT_ORDRE_MISSION IN ('VALIDEE_RH', 'BUDGET_VALIDE')
ORDER BY 
    m.DATE_DEBUT_PREVUE_ORDRE_MISSIO DESC;

-- Commentaire
COMMENT ON TABLE V_MG_RECAP_COMPLET IS 'Vue récapitulative incluant agents + ressources (Police/Chauffeur) avec totaux';
