-- ============================================================================
-- Vue : V_MG_RECAP_MISSION
-- Description : Récapitulatif global des frais par mission avec totaux
-- Utilisation : Tableau de synthèse et statistiques
-- ============================================================================

CREATE OR REPLACE VIEW V_MG_RECAP_MISSION AS
SELECT 
    m.ID_ORDRE_MISSION,
    m.NUMERO_ORDRE_MISSION,
    m.OBJET_ORDRE_MISSION,
    m.DATE_DEBUT_PREVUE_ORDRE_MISSION AS DATE_DEBUT,
    m.DATE_FIN_PREVUE_ORDRE_MISSION AS DATE_FIN,
    m.STATUT_ORDRE_MISSION,
    
    -- Calcul durée
    (m.DATE_FIN_PREVUE_ORDRE_MISSION - m.DATE_DEBUT_PREVUE_ORDRE_MISSION + 1) AS DUREE_JOURS,
    (m.DATE_FIN_PREVUE_ORDRE_MISSION - m.DATE_DEBUT_PREVUE_ORDRE_MISSION) AS DUREE_NUITS,
    
    -- Nombre d'agents
    (SELECT COUNT(DISTINCT ID_AGENT) 
     FROM GM_PARTICIPER 
     WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION) AS NOMBRE_AGENTS,
    
    -- Totaux par catégorie
    NVL((SELECT SUM(MONTANT_PREVU_FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 1), 0) AS TOTAL_REPAS,
         
    NVL((SELECT SUM(MONTANT_PREVU_FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 2), 0) AS TOTAL_HEBERGEMENT,
         
    NVL((SELECT SUM(MONTANT_PREVU_FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 3), 0) AS TOTAL_INDEMNITE,
         
    NVL((SELECT SUM(MONTANT_PREVU_FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION
         AND ID_CATEGORIE_FRAIS = 4), 0) AS TOTAL_CARBURANT,
    
    -- Total général
    NVL((SELECT SUM(MONTANT_PREVU_FRAIS_MISSION)
         FROM GM_FRAISMISSION
         WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION), 0) AS TOTAL_GENERAL,
    
    -- Statut calcul
    CASE 
        WHEN EXISTS (SELECT 1 FROM GM_FRAISMISSION WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION)
        THEN 'CALCULE'
        ELSE 'NON_CALCULE'
    END AS STATUT_CALCUL,
    
    -- Date dernier calcul
    (SELECT MAX(DATE_CRE_FRAIS_MISSION)
     FROM GM_FRAISMISSION
     WHERE ID_ORDRE_MISSION = m.ID_ORDRE_MISSION) AS DATE_CALCUL
     
FROM 
    GM_ORDREMISSION m
WHERE 
    m.STATUT_ORDRE_MISSION IN ('VALIDEE_RH', 'BUDGET_VALIDE')
ORDER BY 
    m.DATE_DEBUT_PREVUE_ORDRE_MISSION DESC;

-- Commentaires
COMMENT ON TABLE V_MG_RECAP_MISSION IS 'Vue récapitulative des frais par mission avec totaux par catégorie';
